import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'EN' | 'FR' | 'RW';
type Theme = 'light' | 'dark';

interface AppContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  theme: Theme;
  toggleTheme: () => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  EN: {
    'nav.collection': 'The Collection',
    'nav.amenities': 'Amenities',
    'nav.journal': 'Journal',
    'nav.dashboard': 'Dashboard',
    'nav.signin': 'Sign In',
    'nav.signout': 'Sign Out',
    'hero.refined': 'Refined Living Since 2012',
    'hero.art': 'Art',
    'hero.ofstaying': 'of Staying.',
    'search.location': 'Location',
    'search.checkin': 'Check In - Out',
    'search.guests': 'Guests',
    'search.button': 'Search',
    'home.featured_sub': 'The Collection',
    'home.featured_title': 'Curated Masterpieces',
    'home.explore_all': 'Explore All',
    'home.cta_title': 'Experience RWANDA.',
    'home.cta_sub': 'From city skyline penthouses to serene lakeside retreats.',
    'home.cta_button': 'Start Your Journey',
    'apartment.discover': 'Discover',
    'apartment.guests': 'guests',
    'apartments.title': 'Explore Apartments',
    'apartments.sub': 'Find the perfect space that fits your needs and budget.',
    'apartments.search_placeholder': 'Search by name or location...',
    'apartments.filters': 'Filters',
    'apartments.not_found': 'No apartments found',
    'apartments.try_adjusting': 'Try adjusting your search or filters to find what you\'re looking for.',
    'apartments.private': 'The collection is currently private. Check back soon.',
    'home.hero_tagline': 'Refined Living',
    'home.hero_title_art': 'Art',
    'home.hero_title_ofstaying': 'of Staying.',
    'home.hero_title_pure': 'Pure',
    'home.hero_title_design': 'Design.',
    'home.hero_title_elite': 'Elite',
    'home.hero_title_comfort': 'Comfort.',
    'home.cta_explore': 'Explore Stays',
    'home.cta_view': 'View Design',
    'home.cta_reserve': 'Reserve Now',
    'details.back': 'Back to search',
    'details.capacity': 'CAPACITY',
    'details.verified': 'VERIFIED',
    'details.verified_host': 'Inkindi Host',
    'details.description': 'Description',
    'details.amenities': 'Amenities',
    'details.not_found': 'Apartment not found',
    'booking.confirmed': 'Booking Confirmed!',
    'booking.success_msg': 'We\'ve received your request. Our team will contact you shortly to finalize details.',
    'booking.another': 'Book Another',
    'booking.reserve': 'Reserve Now',
    'booking.processing': 'Processing...',
    'booking.notice': 'You won\'t be charged yet. We\'ll verify availability first.',
    'booking.fullname': 'Full Name',
    'booking.email': 'Email Address',
    'booking.phone': 'Phone Number',
    'search.date_range': 'Today - next week',
    'common.night': 'night',
    'common.location': 'Kigali, Rwanda',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.add': 'Add',
    'common.view': 'View',
    'common.guests': 'Guests',
    'common.price': 'Price',
    'common.location_label': 'Location',
    'common.apartment': 'Apartment',
    'common.actions': 'Actions',
    'common.status': 'Status',
    'common.date': 'Date',
    'admin.manage_apartments': 'Manage Apartments',
    'admin.add_apt_sub': 'Add, edit, or remove your property listings.',
    'admin.add_apt_btn': 'Add Apartment',
    'admin.edit_apt': 'Edit Apartment',
    'admin.add_new_apt': 'Add New Apartment',
    'admin.apt_name': 'Apartment Name',
    'admin.save_apt': 'Save Apartment',
    'admin.update_apt': 'Update Apartment',
    'admin.bookings_title': 'Guest Bookings',
    'admin.bookings_sub': 'Review and manage all apartment reservation requests.',
    'admin.total_price': 'Total Price',
    'admin.no_bookings': 'No bookings yet',
    'admin.no_bookings_msg': 'New reservation requests will appear here.',
    'admin.confirm_delete': 'Are you sure?',
    'admin.dashboard_title': 'Admin Portal',
    'admin.dashboard_sub': 'Access your dashboard to manage apartments and bookings.',
    'admin.review_bookings': 'Review Bookings',
    'admin.review_bookings_sub': 'Monitor guest requests, confirm reservations, and manage the full booking lifecycle.',
    'admin.manage_apts_sub': 'Add new listings, edit existing properties, change pricing, and update availability.',
  },
  FR: {
    'nav.collection': 'La Collection',
    'nav.amenities': 'Équipements',
    'nav.journal': 'Journal',
    'nav.dashboard': 'Tableau de bord',
    'nav.signin': 'Se Connecter',
    'nav.signout': 'Se Déconnecter',
    'hero.refined': 'Vie Raffinée Depuis 2012',
    'hero.art': 'L\'Art',
    'hero.ofstaying': 'de Séjourner.',
    'search.location': 'Emplacement',
    'search.checkin': 'Arrivée - Départ',
    'search.guests': 'Invités',
    'search.button': 'Chercher',
    'home.featured_sub': 'La Collection',
    'home.featured_title': 'Chefs-d\'œuvre Sélectionnés',
    'home.explore_all': 'Tout Explorer',
    'home.cta_title': 'Découvrez le RWANDA.',
    'home.cta_sub': 'Des penthouses urbains aux retraites sereines au bord du lac.',
    'home.cta_button': 'Commencez Votre Voyage',
    'apartment.discover': 'Découvrir',
    'apartment.guests': 'personnes',
    'apartments.title': 'Explorer les Appartements',
    'apartments.sub': 'Trouvez l\'espace idéal qui correspond à vos besoins et à votre budget.',
    'apartments.search_placeholder': 'Rechercher par nom ou emplacement...',
    'apartments.filters': 'Filtres',
    'apartments.not_found': 'Aucun appartement trouvé',
    'apartments.try_adjusting': 'Essayez d\'ajuster vos filtres de recherche pour trouver ce que vous cherchez.',
    'apartments.private': 'La collection est actuellement privée. Revenez bientôt.',
    'home.hero_tagline': 'Vie Raffinée',
    'home.hero_title_art': 'Art',
    'home.hero_title_ofstaying': 'de Séjourner.',
    'home.hero_title_pure': 'Pur',
    'home.hero_title_design': 'Design.',
    'home.hero_title_elite': 'Elite',
    'home.hero_title_comfort': 'Confort.',
    'home.cta_explore': 'Explorer',
    'home.cta_view': 'Voir le Design',
    'home.cta_reserve': 'Réserver',
    'details.back': 'Retour à la recherche',
    'details.capacity': 'CAPACITÉ',
    'details.verified': 'VÉRIFIÉ',
    'details.verified_host': 'Hôte Inkindi',
    'details.description': 'Description',
    'details.amenities': 'Équipements',
    'details.not_found': 'Appartement non trouvé',
    'booking.confirmed': 'Réservation Confirmée !',
    'booking.success_msg': 'Nous avons reçu votre demande. Notre équipe vous contactera sous peu pour finaliser les détails.',
    'booking.another': 'Réserver un autre',
    'booking.reserve': 'Réserver maintenant',
    'booking.processing': 'Traitement...',
    'booking.notice': 'Vous ne serez pas encore facturé. Nous vérifierons d\'abord la disponibilité.',
    'booking.fullname': 'Nom Complet',
    'booking.email': 'Adresse E-mail',
    'booking.phone': 'Numéro de Téléphone',
    'search.date_range': 'Aujourd\'hui - la semaine prochaine',
    'common.night': 'nuit',
    'common.location': 'Kigali, Rwanda',
    'common.search': 'Chercher',
    'common.filter': 'Filtrer',
    'common.cancel': 'Annuler',
    'common.save': 'Enregistrer',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.add': 'Ajouter',
    'common.view': 'Voir',
    'common.guests': 'Invités',
    'common.price': 'Prix',
    'common.location_label': 'Emplacement',
    'common.apartment': 'Appartement',
    'common.actions': 'Actions',
    'common.status': 'Statut',
    'common.date': 'Date',
    'admin.manage_apartments': 'Gérer les Appartements',
    'admin.add_apt_sub': 'Ajoutez, modifiez ou supprimez vos annonces.',
    'admin.add_apt_btn': 'Ajouter un Appartement',
    'admin.edit_apt': 'Modifier l\'Appartement',
    'admin.add_new_apt': 'Nouvel Appartement',
    'admin.apt_name': 'Nom de l\'Appartement',
    'admin.save_apt': 'Enregistrer l\'Appartement',
    'admin.update_apt': 'Mettre à jour l\'Appartement',
    'admin.bookings_title': 'Réservations des Clients',
    'admin.bookings_sub': 'Consultez et gérez toutes les demandes de réservation.',
    'admin.total_price': 'Prix Total',
    'admin.no_bookings': 'Aucune réservation',
    'admin.no_bookings_msg': 'Les nouvelles demandes apparaîtront ici.',
    'admin.confirm_delete': 'Êtes-vous sûr ?',
    'admin.dashboard_title': 'Portail Admin',
    'admin.dashboard_sub': 'Accédez à votre tableau de bord pour gérer les appartements et les réservations.',
    'admin.review_bookings': 'Réviser les Réservations',
    'admin.review_bookings_sub': 'Surveiller les demandes, confirmer les réservations et gérer le cycle de vie.',
    'admin.manage_apts_sub': 'Ajoutez de nouvelles annonces, modifiez les propriétés et mettez à jour la disponibilité.',
  },
  RW: {
    'nav.collection': 'Ibyegeranyo',
    'nav.amenities': 'Ibikoresho',
    'nav.journal': 'Ikinyamakuru',
    'nav.dashboard': 'Igenzura',
    'nav.signin': 'Injira',
    'nav.signout': 'Sohoka',
    'hero.refined': 'Ubuzima Bwiza Kuva Muri 2012',
    'hero.art': 'Ubuhanzi',
    'hero.ofstaying': 'bwo Kuba.',
    'search.location': 'Aho herereye',
    'search.checkin': 'Kwinjira - Gusohoka',
    'search.guests': 'Abashyitsi',
    'search.button': 'Shaka',
    'home.featured_sub': 'Ibyegeranyo Byacu',
    'home.featured_title': 'Ibyiza Byatoranyijwe',
    'home.explore_all': 'Reba Byose',
    'home.cta_title': 'Sura u RWANDA.',
    'home.cta_sub': 'Kuva mu mazu maremare y\'umujyi kugeza ku mazu atuje ku nkombe z\'ikiyaga.',
    'home.cta_button': 'Tangira Rugendo Rwawe',
    'apartment.discover': 'Reba Byinshi',
    'apartment.guests': 'abantu',
    'apartments.title': 'Shaka Inzu',
    'apartments.sub': 'Shaka ahantu hakubereye hano muri aka karere.',
    'apartments.search_placeholder': 'Shakisha izina cyangwa aho iherereye...',
    'apartments.filters': 'Imiyoboro',
    'apartments.not_found': 'Nta nzu n’imwe yabonetse',
    'apartments.try_adjusting': 'Gerageza guhindura ibyo ushakisha kugirango ubone ibyo ushaka.',
    'apartments.private': 'Inzu ntabwo zirashyirwa hanze. Garuka vuba.',
    'home.hero_tagline': 'Imibereho Myiza',
    'home.hero_title_art': 'Ubuhanzi',
    'home.hero_title_ofstaying': 'bwo Kuba.',
    'home.hero_title_pure': 'Igishushanyo',
    'home.hero_title_design': 'Cyiza.',
    'home.hero_title_elite': 'Uruhushya',
    'home.hero_title_comfort': 'Rwiza.',
    'home.cta_explore': 'Shaka Inzu',
    'home.cta_view': 'Reba Igicapo',
    'home.cta_reserve': 'Tabira None',
    'details.back': 'Subira inyuma',
    'details.capacity': 'IKINYAGU',
    'details.verified': 'BYEMEJE',
    'details.verified_host': 'Inkindi Host',
    'details.description': 'Ibisobanuro',
    'details.amenities': 'Ibikoresho',
    'details.not_found': 'Inzu ntiyabonetse',
    'booking.confirmed': 'Gusaba Kwemejwe!',
    'booking.success_msg': 'Twabonye ubusabe bwawe. Tuzakubwira vuba ibindi bisobanuro.',
    'booking.another': 'Shaka Indi Nzu',
    'booking.reserve': 'Tabira None',
    'booking.processing': 'Tugikora...',
    'booking.notice': 'Ntabwo urishyura. Tuzabanza turebe niba inzu ihari.',
    'booking.fullname': 'Amazina Yombi',
    'booking.email': 'Imeyili',
    'booking.phone': 'Nimero ya Terefone',
    'search.date_range': 'Uyu munsi - icyumweru gitaha',
    'common.night': 'ijoro',
    'common.location': 'Kigali, Rwanda',
    'common.search': 'Shakisha',
    'common.filter': 'Akayunguruzo',
    'common.cancel': 'Reka',
    'common.save': 'Bika',
    'common.edit': 'Hindura',
    'common.delete': 'Siba',
    'common.add': 'Ongeraho',
    'common.view': 'Reba',
    'common.guests': 'Abashyitsi',
    'common.price': 'Ikiguzi',
    'common.location_label': 'Aho herereye',
    'common.apartment': 'Inzu',
    'common.actions': 'Ibikorwa',
    'common.status': 'Imiterere',
    'common.date': 'Itariki',
    'admin.manage_apartments': 'Genzura Amazu',
    'admin.add_apt_sub': 'Ongeraho, hindura cyangwa siba inzu zawe.',
    'admin.add_apt_btn': 'Ongeraho Inzu',
    'admin.edit_apt': 'Hindura Inzu',
    'admin.add_new_apt': 'Inzu nshya',
    'admin.apt_name': 'Izina ry\'Inzu',
    'admin.save_apt': 'Bika Inzu',
    'admin.update_apt': 'Vugurura Inzu',
    'admin.bookings_title': 'Rezervasyon z\'Abashyitsi',
    'admin.bookings_sub': 'Reba kandi ugenzure ibyifuzo byose by\'abashyitsi.',
    'admin.total_price': 'Igiciro Cyose',
    'admin.no_bookings': 'Nta rezervasyon ziraba',
    'admin.no_bookings_msg': 'Ibyifuzo bishya bizagaragara hano.',
    'admin.confirm_delete': 'Urabyemeje?',
    'admin.dashboard_title': 'Igenzura rya Admin',
    'admin.dashboard_sub': 'Injira hano kugirango ugenzure amazu n\'ama rezervasyon.',
    'admin.review_bookings': 'Genzura Rezervasyon',
    'admin.review_bookings_sub': 'Kurikirana ibyifuzo by\'abashyitsi kandi wemeze ama rezervasyon.',
    'admin.manage_apts_sub': 'Ongeraho inzu nshya, hindura zihari, cyangwa vugurura igiciro.',
  }
};

const AppContext = createContext<AppContextType | undefined>(undefined);

export function AppProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('EN');
  const [theme, setTheme] = useState<Theme>('dark');

  const toggleTheme = () => {
    setTheme(prev => prev === 'dark' ? 'light' : 'dark');
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  useEffect(() => {
    const root = window.document.documentElement;
    if (theme === 'dark') {
      root.classList.add('dark');
      root.style.backgroundColor = '#000000';
      root.style.color = '#ffffff';
    } else {
      root.classList.remove('dark');
      root.style.backgroundColor = '#ffffff';
      root.style.color = '#000000';
    }
  }, [theme]);

  return (
    <AppContext.Provider value={{ language, setLanguage, theme, toggleTheme, t }}>
      {children}
    </AppContext.Provider>
  );
}

export function useApp() {
  const context = useContext(AppContext);
  if (context === undefined) {
    throw new Error('useApp must be used within an AppProvider');
  }
  return context;
}
